# Generated by Django 2.1.4 on 2019-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmName', models.CharField(help_text='电影名字', max_length=50)),
                ('filmIcon', models.ImageField(null=True, upload_to='film_icon')),
                ('score', models.CharField(max_length=50)),
                ('filmTime', models.CharField(help_text='上映时间', max_length=50)),
                ('brief', models.TextField(help_text='简介', max_length=1000)),
                ('comment', models.TextField(max_length=2000)),
            ],
        ),
    ]
