# Generated by Django 2.1.4 on 2019-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
