# Generated by Django 2.1.4 on 2019-01-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0002_movies_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='comment',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
