# Generated by Django 2.1.4 on 2019-01-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmIcon', models.ImageField(null=True, upload_to='collect_icon')),
                ('score', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.AddField(
            model_name='collect',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmapp.Movie'),
        ),
    ]
