# Generated by Django 2.1.4 on 2019-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0005_auto_20190103_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='film',
        ),
        migrations.AddField(
            model_name='collect',
            name='colfilmName',
            field=models.CharField(help_text='电影名字', max_length=50, null=True),
        ),
    ]
