# Generated by Django 2.1.4 on 2019-01-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0006_auto_20190103_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='colfilmName',
            new_name='filmName',
        ),
    ]
