# Generated by Django 2.1.4 on 2019-01-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0007_auto_20190103_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
