# Generated by Django 2.1.4 on 2019-01-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0008_movie_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='filmIcon',
            field=models.ImageField(null=True, upload_to='film_icon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickIcon',
            field=models.ImageField(null=True, upload_to='film_icon'),
        ),
    ]
