# Generated by Django 2.1.4 on 2019-01-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0011_auto_20190104_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
