# Generated by Django 2.1.4 on 2019-01-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0012_auto_20190104_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmName', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmapp.Movie')),
            ],
        ),
    ]
