# Generated by Django 2.1.4 on 2019-01-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0014_auto_20190104_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
