# Generated by Django 2.1.4 on 2019-01-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0016_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='user',
        ),
    ]
