# Generated by Django 2.1.4 on 2019-01-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmapp', '0017_remove_collect_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmapp.Profile'),
        ),
    ]
